#! /bin/bash
# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/bashrc.pre.bash" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/bashrc.pre.bash"

# try -s \
#   || return

# shopt -s checkgid
# shopt -s history
# shopt -s append

# export \
#   HISTFILE="$HOME/.local/share/cmd_hist" \
#   HISTSIZE=10000 \
#   HISTFILESIZE=5000 \
#   HISTCONTROL=ignoreboth

export DFD="$HOME/.config/"
export LOC="$HOME/.local/"
export CHD="$HOME/.cache/"
# ~/.bashrc
#

# . "$HOME/.fig/shell/bashrc.pre.bash"
alias ez="vim ~/.zshrc"
alias sz="source ~/.zshrc"
alias eb="vim ~/.bashrc"
alias sb="source ~/.bashrc"
alias lv="lvim"
alias nv="nvim"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
[[ -f ~/.welcome_screen ]] && . ~/.welcome_screen

_set_liveuser_PS1() {
  PS1='[\u@\h \W]\$ '
  if [ "$(whoami)" = "liveuser" ]; then
    local iso_version="$(grep ^VERSION= /usr/lib/endeavouros-release 2>/dev/null | cut -d '=' -f 2)"
    if [ -n "$iso_version" ]; then
      local prefix="eos-"
      local iso_info="$prefix$iso_version"
      PS1="[\u@$iso_info \W]\$ "
    fi
  fi
}
_set_liveuser_PS1
unset -f _set_liveuser_PS1

ShowInstallerIsoInfo() {
  local file=/usr/lib/endeavouros-release
  if [ -r $file ]; then
    cat $file
  else
    echo "Sorry, installer ISO info is not available." >&2
  fi
}

# alias ls='ls --color=auto'
# alias ll='ls -lav --ignore=..' # show long listing of all except ".."
# alias l='ls -lav --ignore=.?*' # show long listing but no hidden dotfiles except "."

[[ "$(whoami)" = "root" ]] && return

[[ -z "$FUNCNEST" ]] && export FUNCNEST=100 # limits recursive functions, see 'man bash'

## Use the up and down arrow keys for finding a command in history
## (you can write some initial letters of the command first).
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

################################################################################
## Some generally useful functions.
## Consider uncommenting aliases below to start using these functions.
##
## October 2021: removed many obsolete functions. If you still need them, please look at
## https://github.com/EndeavourOS-archive/EndeavourOS-archiso/raw/master/airootfs/etc/skel/.bashrc

# _open_files_for_editing() {
#   # Open any given document file(s) for editing (or just viewing).
#   # Note1:
#   #    - Do not use for executable files!
#   # Note2:
#   #    - Uses 'mime' bindings, so you may need to use
#   #      e.g. a file manager to make proper file bindings.
#
#   if [ -x /usr/bin/exo-open ]; then
#     echo "exo-open $@" >&2
#     setsid exo-open "$@" >&/dev/null
#     return
#   fi
#   if [ -x /usr/bin/xdg-open ]; then
#     for file in "$@"; do
#       echo "xdg-open $file" >&2
#       setsid xdg-open "$file" >&/dev/null
#     done
#     return
#   fi
#
#   echo "$FUNCNAME: package 'xdg-utils' or 'exo' is required." >&2
# }
#
#------------------------------------------------------------

## Aliases for the functions above.
## Uncomment an alias if you want to use it.
##

# alias ef='_open_files_for_editing'     # 'ef' opens given file(s) for editing
# alias pacdiff=eos-pacdiff
################################################################################

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# source /home/clp/.config/broot/launcher/bash/br

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/clp/.config/anaconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/home/clp/.config/anaconda/etc/profile.d/conda.sh" ]; then
#         . "/home/clp/.config/anaconda/etc/profile.d/conda.sh"
#     else
#         export PATH="/home/clp/.config/anaconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<

eval "$(starship init bash)"
eval "$(zoxide init bash)"
eval "$(direnv hook bash)"
eval "$(atuin init bash)"
eval "$(navi widget bash)"
eval "$(mcfly init bash)"

alias cvim="nvim --clean -u ~/.config/cvim/init.lua"
alias taplo="/home/clp/.cargo/bin/taplo"

# source "$HOME/.config/.secrets.sh"

eval "$(navi widget bash)"
alias python3="/opt/homebrew/bin/python3"
alias pip3="/opt/homebrew/bin/pip3"
alias python="/opt/homebrew/bin/python"
alias pip3="/opt/homebrew/bin/pip"
export PATH="$PATH:/opt/homebrew/opt/llvm/bin"

export PATH="$PATH:$HOME/.local/share/nvim/mason/bin"
export ONYX_PATH="/Users/clp/.onyx"
export PATH="$ONYX_PATH:$PATH"
export PATH="$PATH:/Users/clp/.local/share/nelua-lang/"
export PATH="$PATH:/opt/homebrew/opt/llvm/bin"
export PATH="$PATH:/opt/homebrew/opt/llvm/Toolchain/bin"
export PKG_CONFIG_PATH="/opt/homebrew/opt/pkg-config/bin/pkg-config"
alias qtb="qutebrowser --qt-wrapper"
export PATH="$PATH:/opt/homebrew/bin/hx"
# . "$HOME/.fig/shell/bashrc.post.bash"

# alias ls='lsd --group-dirs first --date relative --color always'
# alias ll='lsd --group-dirs first --date relative --color always -l'
# alias la='lsd --group-dirs first --date relative --color always -a'
alias ls="eza --color-scale-mode=gradient --hyperlink --group-directories-first --icons=always  --git -h --color-scale=all -F=always"
alias la="eza --color-scale-mode=gradient --hyperlink --group-directories-first --icons=always  --git -h --color-scale=all -F=always -a"
alias ll="eza -l -h"
alias lt="eza -T --recurse --icons --group-directories-first --classify"

alias du="ncdu --color dark -rr -x --exclude .git"
alias cat="bat"

alias rm="rm -irf"

# add starship
eval "$(starship init bash)"

tere() {
  local result=$(command tere "$@")
  [ -n "$result" ] && cd -- "$result"
}

# Amazon Q post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/bashrc.post.bash" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/bashrc.post.bash"
. $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
source /opt/homebrew/share/bash-completion/bash_completion
# eval "$(direnv hook bash)"
# alias emacs="emacs-29.2"
alias yf="yazi"
alias xf="xplr"
alias rf="ranger"
alias lf="lf"
alias sf="spf"
alias jf="joshuto"
alias ff="fff"
alias zj="zellij"
alias cm="chezmoi"
alias ca="chezmoi add"
alias ced="chezmoi edit"
alias ce="chezmoi edit --apply"
alias cew="chezmoi edit --watch"
alias cdi="chezmoi diff"
alias cl="chezmoi -v apply"
alias ccd="chezmoi cd"
alias cup="chezmoi update"
alias cez="chezmoi edit --apply ~/.zshrc"
alias ceb="chezmoi edit --apply ~/.bashrc"
alias cet="chezmoi edit --apply ~/.tmux.conf"
alias cev="chezmoi edit --apply ~/.vimrc"
alias gaa="git add --all"
alias gpom="git push origin master"
alias cf="chezmoi forget"
