# theme = "ayu-mirage"
# theme = "catppuccin_macchiato" # theme = "kaolin-valley-dark" # theme = "ayu-evolve"
# theme = "gruvbox_dark_hard"
# jheme = "everblush"
# theme = "ayu_evolve"
# theme =  # theme = "everforest-dark"

# theme = "base16-default"
 # theme = "kanagawa"
# theme = "ayu_mirage"
# theme = "tokyonight_storm"
theme = "tokyonight_storm"
# theme = "autumn"

[editor]
scrolloff = 5
true-color = true
bufferline = "always"
rulers = [120]
scroll-lines = 3
mouse = true
middle-click-paste = true
shell = ["zsh", "-c"]
line-number = "relative"   #absolute
cursorline = true
cursorcolumn = false
auto-completion = true
preview-completion-insert = true
auto-info = true
completion-trigger-len = 1
# popup-border = true
# indent-heuristic = 'tree-sitter'
completion-replace = false
undercurl = true
auto-format = false
color-modes = true
text-width = 80
idle-timeout = 0
# inset-final-newline = true
# indent-heuristic = "hybrid"
# popup-border = "all" # "popyp" "menu" "all" "none"
default-line-ending = "native"
# workspace-lsp-roots = [
#   
# ]

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 1

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25         # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""   # set wrap-indicator to "" to hide it

[editor.smart-tab]
enable = true
supersede-menu = false
smart-case = true


# [editor.gutters.line-numbers]
# min-width = 1

[editor.lsp]
enable = true
display-inlay-hints = true
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
goto-reference-include-declaration = true
snippets = true


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-modification-indicator",
  "read-only-indicator",
  "file-name",
  "separator",
  "file-type",
  "file-encoding",
  "file-line-ending",
  "register",
  "version-control",
]
center = [
"diagnostics", 
"spacer",
"workspace-diagnostics"]
right = [
  "selections",
  "primary-selection-length",
  "separator",
  "position",
  "spacer",
  "position-percentage",
  "spacer",
  "separator",
  "total-line-numbers",
  "spinner",
  "version-control",
  "mode",
]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"


# [editor.auto-save]
# focus-lost = true
# after-delay.timeout = 3000
# after-delay.enable = true

[editor.file-picker]
hidden = false
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
# max-depth = "None"


# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'

# [keys.normal]
# g = { "ret" = "code_action" } # Maps `ga` to show possible code actions
# "minus" = { "minus" = ":hspuit", "plus" = ":vsplit"}
# H = { c = ":open ~/.config/helix/config.toml", l = ":open ~/.config/helix/languages.toml"}
# "ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
# "plus" = [":open ~/.vimrc"]
# "tab" = ["goto_next_diag"]
# "s-tab" = ["goto_prev_diag"]
[keys.normal]
C-e = ["align_view_bottom", "move_line_down" ]
C-y = ["align_view_top", "move_line_up" ]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"C-w" = ":buffer-close"
"C-r" = "repeat_last_motion"
"C-S-p" = ["command_palette"]
"ret" = [
  "open_below",
  "normal_mode",
] # Maps the enter key to open_below then re-enter normal mode
"S-ret" = ["command_palette"] # TODO
"P" = "extend_line_above"
"C-ret" = ["command_palette"] # TODO
"C-S-ret" = ["command_palette"] # TODO
"S-backspace" = [":sh ls"] # WORKS
"C-S-backspace" = [":sh echo 'WHOOOOO'"] # WORKS
C-S-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
";" = ["command_mode"]
"<" = []
">" = []
"{" = ["goto_first_diag"]
"}" = ["goto_last_diag"]
")" = ["goto_next_buffer"]
"(" = ["goto_previous_buffer"]
"H" = ["goto_previous_buffer"]
"L" = ["goto_next_buffer"]
"C-h" = ["hover"]
"X" = ["extend_line_up", "extend_to_line_bounds"]
"V" = ["extend_to_line_bounds"]
"B" = ["no_op"]
"S-tab" = ["goto_prev_diag"]
"tab" = ["goto_next_diag"]
"S-h" = [":buffer-previous"]
"S-l" = [":buffer-next"]
"S-space" = ["command_palette"]

# "gt" = "buffer_next"
# "lt" = "buffer_prev"
# "enter" = ["select_references_to_symbol_under_cursor"]

[keys.normal."C-space"]
C-space = ["command_palette"]

[keys.normal."space"]
"C-space" = ["completion"]
"S-c" = [":buffer-close"]
"S-d" = [":redraw"]
"S-r" = ["rename_symbol"]
"S-w" = [":write-all!"]
"S-q" = [":write-quit-all!"]
"backspace" = ["last_picker"]
"S-backspace" = ["goto_last_accessed_file"]
")" = ["goto_next_function"]
"(" = ["goto_prev_function"]
"[" = ["goto_prev_class"]
"]" = ["goto_next_class"]
"{" = ["goto_prev_parameter"]
"t" = ["goto_next_test"]
"T" = ["goto_prev_test"]
"p" = ["goto_next_paragraph"]
"P" = ["goto_prev_paragraph"]
"c" = ["goto_next_change"]
"C" = ["goto_prev_change"]
";" = ["command_palette"]
":" = ["command_palette"]
"/" = ["global_search"]
"?" = ["rename_symbol"]
"minus" = "hsplit"
"_" = "vsplit"
"space" = [":lsp-workspace-command"]
"S-space" = ["command_palette"]
a = "code_action"
b = "buffer_picker"
f = ["file_picker"]
F = ["file_picker_in_current_directory"]
"." = ["file_picker_in_current_directory"]
j = "jumplist_picker"
# "g" = "changed_file_picker"
"S" = ["workspace_symbol_picker"]
"d" = ["diagnostics_picker"]
"D" = ["workspace_diagnostics_picker"]
"C-k" = ["jump_view_up"]
"C-h" = ["jump_view_left"]
"C-l" = ["jump_view_right"]
"C-j" = ["jump_view_down"]
"C-S-k" = ["jump_view_up"]
"C-S-h" = ["jump_view_left"]
"C-S-l" = ["jump_view_right"]
"C-S-j" = ["jump_view_down"]
"S-tab" = ["goto_first_diag"]
"tab" = ["goto_last_diag"]
  
[keys.normal.space.s]
h = ["hover"]
a = ["code_action"]
s = ["symbol_picker"]
S = ["workspace_symbol_picker"]
d = ["diagnostics_picker"]
D = ["workspace_diagnostics_picker"]
c = ["command_palette"]
b = ["buffer_picker"]
j = ["jumplist_picker"]
l = [":lsp-workspace-command"]
f = ["file_picker"]
F = ["file_picker_in_current_directory"]
"." = ["file_picker_in_current_buffer_directory"]
backspace = ["last_picker"]


# "C-S-esc" = "extend_line" # Maps Control-Shift-Escape to extend_line
[keys.normal."C-c"]
"C-c" = ["hover"]

[keys.normal."C-s"]
"C-s" = ["hover"]

[keys.normal."C-b"]
"C-c" = ["hover"]

[keys.normal."C-x"]
"C-c" = ["hover"]
"C-x" = ["wclose"]
"C-o" = ["wonly"]

[keys.normal."C-v"]
"C-c" = ["hover"]

[keys.normal.","]
C = [":config-open"]
L = [":o ~/.config/helix/languages.toml"]
R = [":config-reload"]
o = ":config-open"
w = ":config-open-workspace"
l = ":log-open"
r = ":config-reload"
D = ":redraw"
"," = ["hover"]
"." = ["code_action"]
"space" = ["select_references_to_symbol_under_cursor"]
"C-k" = ["jump_view_up"]
"C-h" = ["jump_view_left"]
"C-l" = ["jump_view_right"]
"C-j" = ["jump_view_down"]
"C-S-k" = ["jump_view_up"]
"C-S-h" = ["jump_view_left"]
"C-S-l" = ["jump_view_right"]
"C-S-j" = ["jump_view_down"]
"minus" = [":hsplit-new"]
"_" = [":vsplit-new"]
"u" = [":update"]
"p" = [":pwd"]
"s" = [":sort"]
"S" = [":rsort"]
"F" = [":reflow"]
"/" = ["global_search"]
"d" = [":dbg"]
"e" = [":debug-eval"]

[keys.normal."v"]
"k" = ["half_page_down"]
"j" = ["half_page_up"]
"K" = ["page_up"]
"J" = ["page_down"]
"C-j" = ["align_view_bottom"]
"C-k" = ["align_view_top"]
"c" = ["align_view_center"]
"m" = ["align_view_middle"]

[keys.normal."\\"]
"\\" = ["rotate_view"]
"." = [":lat"]
"," = [":ear"]
"f" = [":fmt"]
"n" = [":new"]

[keys.normal.g]
"ret" = ["goto_file_start"]
G = ["goto_file_end"]
d = ["goto_definition"]
D = ["goto_type_definition"]
y = ["goto_type_definition"]
"i" = ["goto_implementation"]
"r" = ["goto_reference"]


[keys.normal.g.c]
c = ["toggle_comments"]


[keys.normal.","."g"]
a = ["code_action"]
p = ["align_view_middle"]
h = ["hover"]
d = [":change-current-directory ~/.config"]
c = [":change-current-directory ~/.config/helix"]

[keys.select."g"]
"c" = ["toggle_comments"]

[keys.insert]
"C-x" = [":lsp-workspace-command"]
"C-space" = ["completion"]
"S-space" = ["command_palette"]
"C-;" = ["normal_mode", "command_mode"]
"C-S-;" = ["normal_mode", "command_palette"]
"C-c" = ["hover"]
"C-a" = ["code_action"]
"C-k" = ["jump_view_up"]
"C-h" = ["jump_view_left"]
"C-l" = ["jump_view_right"]
"C-j" = ["jump_view_down"]
"C-S-k" = ["jump_view_up"]
"C-S-h" = ["jump_view_left"]
"C-S-l" = ["jump_view_right"]
"C-S-j" = ["jump_view_down"]
"S-esc" = ["no_op"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
"A-x" = ["normal_mode", "command_palette"]   # Maps Alt-X to enter normal mode
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode
# k = { j = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal."C"]
m = ":run-shell-command make"
j = ":run-shell-command just"

[keys.normal."+"]
m = ":run-shell-command make"
j = ":run-shell-command just"

[keys.normal."+".c]
b = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"
r = ":run-shell-command cargo run"
R = ":run-shell-command cargo run --release"
c = ":run-shell-command cargo check"
l = ":run-shell-command cargo clean"

# [keys.normal.space]
# "ret" = "shell_pipe"
# C = ":open ~/.config/helix/config.toml" 

# "semicolon" = "command"

[keys.normal.space.h]
d = ":cd ~/.config/helix"
D = [":cd ~/.config/helix", "file_picker_in_current_directory"]
z = ":open ~/.zshrc"
f = ":open ~/.config/fish/config.fish"
b = ":open ~/.bashrc"
C-n = ":open ~/.config/nushell/config.nu"
x = ":open ~/.xonshrc"
T = ":open ~/.config/wezterm/wezterm.lua"
s = ":open ~/.config/starship.toml"
k = ":open ~/.config/kitty/kitty.conf"
a = ":open ~/.config/alacritty/alacritty.toml"
e = ":open ~/.config/elvish/rc.elv"
C-o = ":open ~/.config/helix/config.toml"      # Maps the Control-o to opening of the helix config file
V = ":open ~/.vimrc"
i = ":open ~/.ideavimrc"
c = ":open ~/.config/helix/config.toml"
l = ":open ~/.config/lvim/config.lua"
n = ":open ~/.config/nvim/init.lua"
t = ":open ~/.config/tmux/tmux.conf"
v = ":open ~/.config/vnim/init.lua"
r = ":reload"
o = ":config-open"
w = ":config-open-workspace"

[keys.normal."minus"]
"minus" = ":hsplit"
"+" = ":vsplit"


[keys.normal.space.r]
r = "shell_pipe"
