# User preference
# ───────────────

set-option global makecmd 'make -j8'
set-option global grepcmd 'rg -n'
set-option global lintcmd 'make -j8'
set-option global ui_options terminal_status_on_top=false
hook global ModuleLoaded clang %{ set-option global clang_options -std=c++20 }
hook global ModuleLoaded tmux %{ alias global terminal tmux-terminal-vertical }

colorscheme ayu-mirage


set-face global CurSearch +u

hook global RegisterModified '/' %{ add-highlighter -override global/search regex "%reg{/}" 0:CurSearch }

hook global BufCreate .* %[
    add-highlighter buffer/ number-lines -relative -hlcursor
    add-highlighter buffer/ wrap
]

# Enable editor config
# ────────────────────

# hook global BufOpenFile .* %{ editorconfig-load }
# hook global BufNewFile .* %{ editorconfig-load }

# Filetype specific hooks
# ───────────────────────

hook global WinSetOption filetype=(c|cpp) %{
    clang-enable-autocomplete 
    clang-enable-diagnostics
    alias window lint clang-parse
    alias window lint-next-error clang-diagnostics-next
}

hook global WinSetOption filetype=python %{
    jedi-enable-autocomplete
    lint-enable
    set-option global lintcmd 'flake8'
}

map -docstring "xml tag objet" global object t %{c<lt>([\w.]+)\b[^>]*?(?<lt>!/)>,<lt>/([\w.]+)\b[^>]*?(?<lt>!/)><ret>}

# Highlight the word under the cursor
# ───────────────────────────────────

set-face global CurWord +b

hook global NormalIdle .* %{
    eval -draft %{ try %{
        exec ,<a-i>w <a-k>\A\w+\z<ret>
        add-highlighter -override global/curword regex "\b\Q%val{selection}\E\b" 0:CurWord
    } catch %{
        add-highlighter -override global/curword group
    } }
}

# Switch cursor color in insert mode
# ──────────────────────────────────

set-face global InsertCursor default,green+B

hook global ModeChange .*:.*:insert %{
    set-face window PrimaryCursor InsertCursor
    set-face window PrimaryCursorEol InsertCursor
}

hook global ModeChange .*:insert:.* %{ try %{
    unset-face window PrimaryCursor
    unset-face window PrimaryCursorEol
} }

# Custom mappings
# ───────────────

map global normal = ':prompt math: %{exec "a%val{text}<lt>esc>|bc<lt>ret>"}<ret>'

# System clipboard handling
# ─────────────────────────


evaluate-commands %sh{
    if [ -n "$SSH_TTY" ]; then
        copy='printf "\033]52;;%s\033\\" $(base64 | tr -d "\n") > $( [ -n "$kak_client_pid" ] && echo /proc/$kak_client_pid/fd/0 || echo /dev/tty )'
        paste='printf "paste unsupported through ssh"'
        backend="OSC 52"
    else
        case $(uname) in
            Linux)
                if [ -n "$WAYLAND_DISPLAY" ]; then
                    copy="wl-copy -p"; paste="wl-paste -p"; backend=Wayland
                else
                    copy="xclip -i"; paste="xclip -o"; backend=X11
                fi
                ;;
            Darwin)  copy="pbcopy"; paste="pbpaste"; backend=OSX ;;
        esac
    fi

    printf "map global user -docstring 'paste (after) from clipboard' p '<a-!>%s<ret>'\n" "$paste"
    printf "map global user -docstring 'paste (before) from clipboard' P '!%s<ret>'\n" "$paste"
    printf "map global user -docstring 'yank to primary' y '<a-|>%s<ret>:echo -markup %%{{Information}copied selection to %s primary}<ret>'\n" "$copy" "$backend"
    printf "map global user -docstring 'yank to clipboard' Y '<a-|>%s<ret>:echo -markup %%{{Information}copied selection to %s clipboard}<ret>'\n" "$copy -selection clipboard" "$backend"
    printf "map global user -docstring 'replace from clipboard' R '|%s<ret>'\n" "$paste"
    printf "define-command -override echo-to-clipboard -params .. %%{ echo -to-shell-script '%s' -- %%arg{@} }" "$copy"
}

map global normal <semicolon> : -docstring '; to :'
map global normal -docstring 'buffer prev' '<S-h>' ':buffer-previous<ret>'
map global normal -docstring 'buffer next' '<S-l>' ':buffer-next<ret>'
map global normal -docstring 'comment lines' '#'  %{: comment<ret>}
map global normal <c-q> ": db;q<ret>"
map global normal <c-s> ":w<ret>"



# map global user -docstring 'normal from insert' p '<esc>''#' :comment-line<ret>

map global user -docstring 'next lint error' n ':lint-next-error<ret>'
map global normal <c-p> :lint<ret>

map global user -docstring 'gdb helper mode' g ':gdb-helper<ret>'
map global user -docstring 'gdb helper mode (repeat)' G ':gdb-helper-repeat<ret>'

map global user -docstring 'lsp mode' l ':enter-user-mode lsp<ret>'

hook global -always BufOpenFifo '\*grep\*' %{ map global normal <minus> ': grep-next-match<ret>' }
hook global -always BufOpenFifo '\*make\*' %{ map global normal <minus> ': make-next-error<ret>' }

# Enable <tab>/<s-tab> for insert completion selection
# ──────────────────────────────────────────────────────

hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p> }

# Helper commands
# ───────────────

# complete-command -menu find shell-script-candidates %{ ag -g '' --ignore "$kak_opt_ignored_files" }

define-command mkdir %{ nop %sh{ mkdir -p $(dirname $kak_buffile) } }

define-command ide -params 0..1 %{
    try %{ rename-session %arg{1} }

    rename-client main
    set-option global jumpclient main

    rename-client tools
    set-option global toolsclient tools

    rename-client docs
    set-option global docsclient docs
}

define-command delete-buffers-matching -params 1 %{
    evaluate-commands -buffer * %{
        evaluate-commands %sh{ case "$kak_buffile" in $1) echo "delete-buffer" ;; esac }
    }
}

declare-option -hidden str swap_buffer_target
define-command swap-buffer-with -override -params 1 -client-completion %{
    set-option global swap_buffer_target %val{bufname}
    edit -scratch # release current window for other client
    evaluate-commands -client %arg{1} "
        set-option global swap_buffer_target %%val{bufname}
        buffer %opt{swap_buffer_target}
    "
    delete-buffer # delete the temporary scratch buffer
    buffer %opt{swap_buffer_target}
}

declare-option int gdb_server_port 5678
declare-option str gdb_server_cmd "gdbserver :%opt{gdb_server_port}"

define-command gdb-server -params .. %{
    fifo %opt{gdb_server_cmd} %arg{@}
    gdb-session-new -ex "target extended-remote :%opt{gdb_server_port}"
}


declare-option str to_asm_cmd 'g++ -O3 -x c++'
declare-option str to_asm_prelude '
#include <utility>
'
declare-option -hidden int to_asm_timestamp 0

define-command to-asm -params .. -docstring %{
    Compile selected text with using the to_asm_cmd option and display assembly in the *asm* buffer
} %{
    evaluate-commands -save-regs 'ab"|' %{
        execute-keys -save-regs '' y
        set-register a %opt{to_asm_prelude}
        set-register b %opt{to_asm_cmd}
        evaluate-commands -try-client %opt{docsclient} %{
            edit -scratch *asm*
            set-option buffer filetype gas
            execute-keys \%R"aP% "|%reg{b} %arg{@} -S - -o - 2>&1|c++filt<ret>" gg
            try %{ execute-keys -draft \%s^\h*\.cfi_<ret>xd }
        }
    }
}

define-command to-asm-enable -docstring %{
    Automatically run to-asm on the whole buffer after each change
} %{
    remove-hooks window to-asm
    hook -group to-asm window NormalIdle .* %{ try %{
        %sh{ [ $kak_opt_to_asm_timestamp -eq $kak_timestamp ] && echo "fail" || echo "nop" }
        set buffer to_asm_timestamp %val{timestamp}
        evaluate-commands -draft %{
            execute-keys '%'
            to-asm
        }
    } }
}

define-command diff-buffers -override -params 2 %{
    evaluate-commands %sh{
        file1=$(mktemp)
        file2=$(mktemp)
        echo "
            evaluate-commands -buffer '$1' write -force $file1
            evaluate-commands -buffer '$2' write -force $file2
            edit! -scratch *diff-buffers*
            set buffer filetype diff
            set-register | 'diff -u $file1 $file2; rm $file1 $file2'
            execute-keys !<ret>gg
        "
}}

complete-command diff-buffers buffer

define-command clang-format-cursor %{
    exec -draft <percent>| "clang-format --lines=%val{cursor_line}:%val{cursor_line}" <ret>
}

hook global GlobalSetOption 'makecmd=ninja(-build)?\b.*' %{ complete-command make shell-script-candidates %{ $kak_opt_makecmd -t targets | cut -f 1 -d : } }
hook global GlobalSetOption 'makecmd=bazel\b.*' %{ complete-command make shell-script-candidates %{ bazel query //... } }

# Mail
# ────

hook global BufOpenFile .*/mail/.*/(cur|new|tmp)/[^/]+ %{ set-option buffer filetype mail }

# Load local Kakoune config file if it exists
# ───────────────────────────────────────────

# source "%val{config}/plugins/plug.kak/rc/plug.kak"

# # relative line numbers
# hook global BufCreate .* %[
    evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload %{
    # add-highlighter buffer/ numbers -relative -hlcursor
    # add-highlighter buffer/ wrap
}

add-highlighter global/ show-matching

# Disable clippy
set-option global ui_options ncurses_assistant=off

# Set jumpclient
# set-option global semantic-tokens true
#
# plug "ul/kak-lsp" do %{
    # }
set-option global jumpclient jump
plug "andreyorst/fzf.kak" config %{
    map -docstring 'fzf mode' global normal '<c-p>' ': fzf-mode<ret>'
} defer fzf %{
    set-option global fzf_preview_width '65%'
    set-option global fzf_project_use_tilda true
}
    # Set toolsclient
set-option global toolsclient tools
# Set docsclient
set-option global docsclient docs
# Create client with name
map global normal D '<a-l>d' -docstring 'delete to end of line'
map global normal Y '<a-l>y' -docstring 'yank to end of line'
map global normal <a-h> Gi
define-command -docstring "Open a new client with the given name" \
new-client -params 1 %{
    new rename-client %arg{1}
}


# indentation
set-option global tabstop     4
set-option global indentwidth 4
set-option global scrolloff 5,5
# # tabs to spaces
hook global InsertChar \t %{
    exec -draft h@
}

# keep space around cursor
# set-option global scrolloff 10,10

# save on pressing enter
hook global NormalKey <ret> w

# remap grep-jump
map global goto <ret> "<esc><ret>"

# vim old habits
map global normal D '<a-l>d' -docstring 'delete to end of line'
map global normal Y '<a-l>y' -docstring 'yank to end of line'
map global normal <a-h> Gi

# case insensitive search
map global prompt <a-i> "<home>(?i)<end>"

# user mappings
# map global user l -docstring 'lsp' ': enter-user-mode lsp<ret>'

define-command paste %{
    evaluate-commands -save-regs ^ %{
        #Paste
        execute-keys "!pbpaste<ret>"
        #Select 
        execute-keys uU
        #Save selection
        execute-keys -save-regs "" Z
        try %{
            #Remove cariage return before newline
            execute-keys "s\r\n<ret>hd"
        }
        try %{
            #Replace cariage return elsewhere with newline
            execute-keys "zs\r<ret>r<return>"
        }
        #Restore selection
        execute-keys z
    }
}

## clipboard interaction
map global user p -docstring 'paste from clipboard' ': paste<ret>'
map global user y -docstring 'copy to clipboard' '<a-|>pbcopy<ret>'
map global user d -docstring 'cut to clipboard' '|pbcopy<ret>'

# format
# map global user f -docstring 'format buffer' ':format<ret>'

define-command comment %{
    try %{
        execute-keys _
        comment-block
    } catch comment-line
}

define-command -hidden ctags-search-word %{
    try %{
        execute-keys <a-i>w
    }
    execute-keys ": ctags-search "
}

# comment lines
map global user c -docstring 'comment lines' %{: comment<ret>}

# search with c tags
map global goto s -docstring 'search ctags' %{<esc>: ctags-search-word<ret>}

# Delete buffer and quit
map global normal <c-q> ": db;q<ret>"

# Open file in new window
define-command open-in-new-window -params .. -file-completion %{ new edit "%arg{@}"}
alias global e open-in-new-window

# Terminal, used by ide wrapper
define-command _terminal -params .. %{
  shell \
    -export session \
    -export client \
    %sh(echo $TERMINAL) -e %arg(@) \
    %sh(test $# = 0 &&
      echo $SHELL
    )
}

try %{
    require-module x11
    require-module tmux
}
alias global term _terminal

# Define mappings for when repl is used
define-command repl-mappings -params .. %{
    map buffer normal <backspace> ": repl-send-text<ret>"
    repl-new %arg{@}
}

# file types
hook global BufCreate .*\.xsd %{ set buffer filetype xml }

# kakoune language server

# Depends on https://github.com/ul/kak-lsp

# set-option global lsp_server_configuration latex.build.onSave=true
# set-option -add global lsp_server_configuration latex.build.args=["-pdf","-pdflatex\=lualatex","-interaction\=nonstopmode","-synctex\=1","%f"]
# set-option -add global lsp_server_configuration latex.build.forwardSearchAfter=true
# set-option -add global lsp_server_configuration latex.forwardSearch.executable="okular"
# set-option -add global lsp_server_configuration latex.forwardSearch.args=["--noraise","--unique","file:%p#src:%l%f"]

#spell
declare-user-mode spell
map global spell a -docstring 'add to dictionary' ": spell-add<ret>" 
map global spell e -docstring 'enable'  ": spell-enable<ret>"
map global spell r -docstring 'replace' ": spell-replace<ret>"
map global spell n -docstring 'next'    ": spell-next<ret>"
map global spell c -docstring 'clear'   ": spell-clear<ret>"
# map global user s -docstring 'spell' ": enter-user-mode -lock spell<ret>"
declare-option str language en-GB
define-command spell-enable %{
    #hook global WinSetOption filetype=(latex|markdown|git-commit) %{
        hook window BufWritePost .* %{
            spell %opt{language}
        }
    #}
}

set-option global modelinefmt %{{Error}%sh{[ $kak_opt_lsp_diagnostic_error_count -gt 0 ] && echo "$kak_opt_lsp_diagnostic_error_count"}{StatusLineInfo} %sh{ echo $kak_opt_debugger_indicator } {StatusLine}%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]}
# set-option global modelinefmt %{ %sh{ echo $kak_opt_debugger_indicator } {StatusLine}%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]}

# Disable sql highlighting
set global disabled_hooks '(sql-highlight|php-indent|php-trim-indent|php-insert)'

# Use ripgrep instead of grep
set global grepcmd 'rg -n'

# Editorconfig
# hook global BufOpenFile .* editorconfig-load
# hook global BufNewFile .* editorconfig-load

# Plugins
# source "%val{config}/plugins/plug.kak/rc/plug.kak"
# plug "andreyorst/plug.kak" noload
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
}
plug "andreyorst/plug.kak" noload config %{
}
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
}

# eval %sh{kak-lsp}
eval %sh{kak-lsp --kakoune -s $kak_session }
Debug output
nop %sh{ (kak-lsp -s $kak_session -vvv ) > /tmp/kak-lsp.log 2>&1 < /dev/null & }
lsp-enable
hook global WinSetOption filetype=(rust|python|php|haskell|c|cpp|dart|javascript|typescript|nim|toml|yaml|json|markdown|latex|c#|racket) %{
    map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"

map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'
     lsp-enable-window
     lsp-auto-hover-enable
     lsp-auto-signature-help-enable
     set global lsp_hover_anchor true
     hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
     hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
     hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
     hook -once -always window WinSetOption filetype=.* %{
         remove-hooks window semantic-tokens
     }
 }
plug "andreyorst/fzf.kak" do %{
    ls -a
} demand fzf %{
    set-option global fzf_project_use_tilda true
} config %{
    require-module fzf
    map -docstring 'fzf mode' global normal '<c-p>' ': fzf-mode<ret>'
    set-option global fzf_preview_width '65%'
}
# eval %sh{kak-lsp}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
}
map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"

map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

hook global BufSetOption filetype=rust %{
    hook buffer BufWritePre .* lsp-formatting-sync
}
